name: Desktop Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version/tag (e.g. v3.5.8)"
        required: true
      packageManager:
        description: "pnpm version (e.g. pnpm@10.30.1)"
        required: true

env:
  repo_owner: EightDoor
  repo_name: unlock-siyuan

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            kernel_path: "../app/kernel-linux/SiYuan-Kernel"
            build_args: "-s -w -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod"
            electron_args: "dist-linux"
            goos: "linux"
            goarch: "amd64"
            cc_path: "x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc"
            suffix: "linux.tar.gz"
          - os: ubuntu-22.04
            kernel_path: "../app/kernel-linux/SiYuan-Kernel"
            build_args: "-s -w -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod"
            electron_args: "dist-linux"
            goos: "linux"
            goarch: "amd64"
            cc_path: "x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc"
            suffix: "linux.AppImage"
          - os: ubuntu-22.04
            kernel_path: "../app/kernel-linux-arm64/SiYuan-Kernel"
            build_args: "-s -w -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod"
            electron_args: "dist-linux-arm64"
            goos: "linux"
            goarch: "arm64"
            cc_path: "aarch64-linux-musl-cross/bin/aarch64-linux-musl-gcc"
            suffix: "linux-arm64.tar.gz"
          - os: macos-latest
            kernel_path: "../app/kernel-darwin/SiYuan-Kernel"
            build_args: "-s -w -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod"
            electron_args: "dist-darwin"
            goos: "darwin"
            goarch: "amd64"
            suffix: "mac.dmg"
          - os: macos-latest
            kernel_path: "../app/kernel-darwin-arm64/SiYuan-Kernel"
            build_args: "-s -w -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod"
            electron_args: "dist-darwin-arm64"
            goos: "darwin"
            goarch: "arm64"
            suffix: "mac-arm64.dmg"
          - os: windows-latest
            kernel_path: "../app/kernel/SiYuan-Kernel.exe"
            build_args: "-s -w -H=windowsgui -X github.com/siyuan-note/siyuan/kernel/util.Mode=prod"
            electron_args: "dist"
            goos: "windows"
            gobin: "bin"
            mingwsys: "MINGW64"
            goarch: "amd64"
            suffix: "win.exe"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Clone upstream and apply patches
        run: |
          mkdir -p ${{ github.workspace }}/go
          cd ${{ github.workspace }}/repo
          
          git clone --branch ${{ github.event.inputs.version }} --depth=1 https://github.com/siyuan-note/siyuan.git
          cd siyuan
          
          git apply ${{ github.workspace }}/repo/patches/siyuan/mock-vip-user.patch
          git apply ${{ github.workspace }}/repo/patches/siyuan/disable-update.patch
          git apply ${{ github.workspace }}/repo/patches/siyuan/remove-stat.patch
          
          git status

      - name: Set up Cross Compilation Toolchains for Linux
        if: contains(matrix.config.goos, 'linux')
        run: |
          sudo mkdir -p /usr/local/musl
          
          if [ "${{ matrix.config.goarch }}" = "amd64" ]; then
            wget -q https://github.com/appdev/musl-archive/releases/download/latest/x86_64-linux-musl-cross.tgz
            sudo tar -xzf x86_64-linux-musl-cross.tgz -C /usr/local/musl
          elif [ "${{ matrix.config.goarch }}" = "arm64" ]; then
            wget -q https://github.com/appdev/musl-archive/releases/download/latest/aarch64-linux-musl-cross.tgz
            sudo tar -xzf aarch64-linux-musl-cross.tgz -C /usr/local/musl
          fi

      - name: Set up MingGW
        uses: msys2/setup-msys2@v2
        if: contains(matrix.config.goos, 'windows')
        with:
          install: p7zip mingw-w64-x86_64-lua

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ github.workspace }}/repo/siyuan/kernel/go.mod
          cache-dependency-path: "**/*.sum"
      - run: go version

      - name: Set up goversioninfo
        if: contains(matrix.config.goos, 'windows')
        run: go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo && go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo
        working-directory: ${{ github.workspace }}/repo/siyuan/kernel
        env:
          GO111MODULE: on
          CGO_ENABLED: 1
          GOOS: ${{ matrix.config.goos }}
          GOPATH: ${{ github.workspace }}/go
          GOARCH: ${{ matrix.config.goarch }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node pnpm
        run: npm install -g ${{ github.event.inputs.packageManager }}
        working-directory: ${{ github.workspace }}/repo/siyuan/app

      - name: Install Node Dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: ${{ github.workspace }}/repo/siyuan/app

      - name: Building UI
        run: pnpm run build
        working-directory: ${{ github.workspace }}/repo/siyuan/app

      - name: Generate Icon Resource For Windows
        if: contains(matrix.config.goos, 'windows')
        run: ${{ github.workspace }}\go\${{ matrix.config.gobin }}\goversioninfo -platform-specific=true -icon="resource\icon.ico" -manifest="resource\goversioninfo.exe.manifest"
        working-directory: ${{ github.workspace }}/repo/siyuan/kernel

      - name: Clean Build Directories
        if: contains(matrix.config.goos, 'linux')
        run: |
          rm -rf app/build
          rm -rf app/kernel-linux
          rm -rf app/kernel-linux-arm64
        working-directory: ${{ github.workspace }}/repo/siyuan

      - name: Clean Build Directories for macOS
        if: contains(matrix.config.goos, 'darwin')
        run: |
          rm -rf app/build
          rm -rf app/kernel-darwin
          rm -rf app/kernel-darwin-arm64
        working-directory: ${{ github.workspace }}/repo/siyuan

      - name: Clean Build Directories for Windows
        if: contains(matrix.config.goos, 'windows')
        run: |
          rm -rf app/build
          rm -rf app/kernel
        working-directory: ${{ github.workspace }}/repo/siyuan

      - name: Building Kernel
        run: go build --tags fts5 -o "${{ matrix.config.kernel_path }}" -v -ldflags "${{ matrix.config.build_args }}"
        working-directory: ${{ github.workspace }}/repo/siyuan/kernel
        env:
          GO111MODULE: on
          CGO_ENABLED: 1
          GOOS: ${{ matrix.config.goos }}
          GOPATH: ${{ github.workspace }}/go
          GOARCH: ${{ matrix.config.goarch }}
          GOPROXY: https://mirrors.aliyun.com/goproxy/
          CC: ${{ runner.os == 'Linux' && format('/usr/local/musl/{0}', matrix.config.cc_path) || '' }}

      - name: Building Electron
        run: pnpm run ${{ matrix.config.electron_args }}
        working-directory: ${{ github.workspace }}/repo/siyuan/app

      - name: Get Release
        id: get_release
        uses: joutvhu/get-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_name: siyuan-${{ github.event.inputs.version }}-${{ matrix.config.suffix }}
          asset_path: ${{ github.workspace }}/repo/siyuan/app/build/siyuan-*-${{ matrix.config.suffix }}
          asset_content_type: application/octet-stream
